### PR TITLE
Add TGC logo and info

### PR DESCRIPTION
**Pull request by thetorytgcoin**
Pull request closed and reopened

### CODE REVIEW

**Comment by thetorytgcoin** [comment]
0xF26DAAAbaCD44d953551d986F46A68111e53BCA9 The wallet is managed by the foundation and is still recruiting users. We are continuing to recruit, and users will proceed with the liquidity supply to the FIST and TGC pools, which we expect will grow further
and The manager's authority is concentrated, so if there's a problem, please tell me the problem and I'll collect it

**Comment by FstSwapDex** [comment]
Trading can be suspended
Blacklists exist, making buying and selling restricted
0x9b1e4cd195b78da62235b5579359b7fda75d132a
Can the current token contract permissions be explained?

**Comment by thetorytgcoin** [comment]
> Trading can be suspended Blacklists exist, making buying and selling restricted 0x9b1e4cd195b78da62235b5579359b7fda75d132a Can the current token contract permissions be explained?

https://bscscan.com/address/0x9b1e4cd195b78da62235b5579359b7fda75d132a#code
It's the source code.
Can we know if it's a blacklist? We don't know anything about that part.

**Comment by thetorytgcoin** [comment]
> Trading can be suspended Blacklists exist, making buying and selling restricted 0x9b1e4cd195b78da62235b5579359b7fda75d132a Can the current token contract permissions be explained?

Token security audit is currently in progress and can be submitted when completed

**Comment by thetorytgcoin** [comment]
> Trading can be suspended Blacklists exist, making buying and selling restricted 0x9b1e4cd195b78da62235b5579359b7fda75d132a Can the current token contract permissions be explained?

The main authority of the control is in the code, and you can change it if you tell me the problem code

**Comment by FstSwapDex** [comment]
If your token manager, no important changes, can discard it

**Comment by FstSwapDex** [comment]
Besides that, you need to provide hash about fist burning

**Comment by thetorytgcoin** [comment]
> 

Yes, I will delete the owner's authority.

Then is there no problem?

**Comment by thetorytgcoin** [comment]
> Besides that, you need to provide hash about fist burning

If you say there's no problem, we'll incinerate the owner

**Comment by FstSwapDex** [comment]
Yes, if you can burn the admin of the token, we can help you update the logo

**Comment by FstSwapDex** [comment]
We didn't see the 100 fists you submitted for burning, can you provide the hash of the burning fist?

**Comment by thetorytgcoin** [comment]
> Yes, if you can burn the admin of the token, we can help you update the logo

Yes, we will proceed with the incineration today. Let's move on and give them the contact information

**Comment by thetorytgcoin** [comment]
> We didn't see the 100 fists you submitted for burning, can you provide the hash of the burning fist?



> We didn't see the 100 fists you submitted for burning, can you provide the hash of the burning fist?

Can you tell me what the hash of the Burning of 100 FIST means?

**Comment by thetorytgcoin** [comment]
> We didn't see the 100 fists you submitted for burning, can you provide the hash of the burning fist?

I understand. We missed to incinerate 100FIST. Should I proceed with this now too?
Can I proceed with the wallet address of the owner's wallet stamped on the current contact?

**Comment by thetorytgcoin** [comment]
https://bscscan.com/tx/0x7611c9f9043301c515b8b7987a160d259783675f6793712a94dc3ff552384a1b
FIST 100 Burning contract address

**Comment by thetorytgcoin** [comment]
I tried to change the address of the owner's wallet.
The nell address :0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 How should I do the incineration?

**Comment by thetorytgcoin** [comment]
https://bscscan.com/tx/0x8a298902cdddb7070ef5853cd6f3def23f80271eff11feba867e7fa9bc920366
The owner has been incinerated

**Comment by FstSwapDex** [comment]
We have received your request and will update the logo for you soon

**Comment by thetorytgcoin** [comment]
> We have received your request and will update the logo for you soon

Thank you very much.

**Comment by FstSwapDex** [comment]
The current token also has an administrator privilege to suspend trading, please deal with it as soon as possible

**Comment by FstSwapDex** [comment]
0x27c9C808035d0BE2d0E8B4Ade40d232a87191FC1
The creator address still has permission to suspend transactions, please discard as soon as possible

**Pull request merged**
