### PR TITLE
Add TGC logo and info

### PR DESCRIPTION
**Pull request by thetorytgcoin**
0x9B1e4cD195b78Da62235b5579359B7FdA75D132a

### CODE REVIEW

**Comment by FstSwapDex** [comment]
The current token administrator has too much authority, can you consider optimizing the current token administrator?

**Comment by FstSwapDex** [comment]
0xF26DAAAbaCD44d953551d986F46A68111e53BCA9 
The current token has the risk of centralization. Can you explain the actual use of the current address?

**Comment by thetorytgcoin** [comment]
The TCGs that your administrator currently has are: 
0xF26DAAAbaCD44d953551d986F46A68111e53BCA9 wallet does not yet have a TGC in its liquidity pool. We are recruiting more users to provide to TGC and FIST liquidity pools, and the foundation does not move tokens arbitrarily in its wallet

**Comment by thetorytgcoin** [comment]
> The current token administrator has too much authority, can you consider optimizing the current token administrator?

If there is a problem, you can change it

**Pull request closed without merging**
