### PR TITLE
Revert "Add TGC logo and info"

### PR DESCRIPTION
**Pull request by FstSwapDex**
Reverts FstSwapDex/logo#28

### CODE REVIEW

**Comment by FstSwapDex** [comment]
The current token also has an administrator privilege to suspend trading, please deal with it as soon as possible

**Comment by thetorytgcoin** [comment]
> The current token also has an administrator privilege to suspend trading, please deal with it as soon as possible

You have already incinerated ownership and do not have administrative rights. Could you tell me what part it is?

**Comment by FstSwapDex** [comment]
The account address 0x27c9c808035d0be2d0e8b4ade40d232a87191fc1 can pause this contract

**Comment by thetorytgcoin** [comment]
> The account address 0x27c9c808035d0be2d0e8b4ade40d232a87191fc1 can pause this contract

I'll check.

**Comment by thetorytgcoin** [comment]
> The account address 0x27c9c808035d0be2d0e8b4ade40d232a87191fc1 can pause this contract

The change is complete!

**Pull request closed without merging**
